export enum AdoptionRequestErrorsCode {
  MISSING_PREADOPTION_FORM_IN_USER = 'MISSING_PREADOPTION_FORM_IN_USER',
  ALREADY_CREATED_REQUEST_WITH_SAME_AD = 'ALREADY_CREATED_REQUEST_WITH_SAME_AD',
  REQUEST_WITH_SAME_CREATION_USER = 'REQUEST_WITH_SAME_CREATION_USER',
}
