import { Inter } from 'next/font/google';
import { Sidebar } from '@components/Sidebar';
import { DashboardNavbar } from '@components/DashboardNavbar';
import { ChakraProvider } from '@shared/presentation/chakra-ui/chakra-provider';
import '../../global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const DashboardRootLayout = async ({
  children,
}: {
  children: React.ReactNode;
}) => (
  <html lang="en">
    <body className={inter.className}>
      <ChakraProvider>
        <Sidebar navigation={<DashboardNavbar />}>{children}</Sidebar>
      </ChakraProvider>
    </body>
  </html>
);

export default DashboardRootLayout;
