import { headers } from 'next/headers';
import { Inter } from 'next/font/google';
import { userPrivateFinderByEmail } from '@user/application/user-finder-by-email';
import { getSession } from '@shared/presentation/services/auth-service';
import { UserContextProvider } from '@user/presentation/hooks/useUser';
import { User } from '@user/model';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getSession(headers().get('cookie') ?? '');
  let user: Omit<User, 'password'> | null = null;

  if (session?.user?.email) {
    user = await userPrivateFinderByEmail(session?.user?.email as string);
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider initialUser={user}>{children}</UserContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
