export const COUNTRIES = [
  {
    name: {
      de: 'Deutschland',
      en: 'Germany',
      es: 'Alemania',
      fr: 'Allemagne',
      it: 'Germania',
      pt: 'Alemanha',
    },
    isoCode: 'DE',
    flagPath: '/flags/de.svg',
  },
  {
    name: {
      de: 'Niederlande',
      en: 'Netherlands',
      es: 'Países Bajos',
      fr: 'Pays-Bas',
      it: 'Paesi Bassi',
      pt: 'Países Baixos',
    },
    isoCode: 'NL',
    flagPath: '/flags/nl.svg',
  },
  {
    name: {
      de: 'Vereinigtes Königreich',
      en: 'United Kingdom',
      es: 'Reino Unido',
      fr: 'Royaume-Uni',
      it: 'Regno Unito',
      pt: 'Reino Unido',
    },
    isoCode: 'GB',
    flagPath: '/flags/gb.svg',
  },
  {
    name: {
      de: 'Spanien',
      en: 'Spain',
      es: 'España',
      fr: 'Espagne',
      it: 'Spagna',
      pt: 'Espanha',
    },
    isoCode: 'ES',
    flagPath: '/flags/es.svg',
  },
  {
    name: {
      de: 'Irland',
      en: 'Ireland',
      es: 'Irlanda',
      fr: 'Irlande',
      it: 'Irlanda',
      pt: 'Irlanda',
    },
    isoCode: 'IE',
    flagPath: '/flags/ie.svg',
  },
  {
    name: {
      de: 'Frankreich',
      en: 'France',
      es: 'Francia',
      fr: 'France',
      it: 'Francia',
      pt: 'França',
    },
    isoCode: 'FR',
    flagPath: '/flags/fr.svg',
  },
  {
    name: {
      de: 'Polen',
      en: 'Poland',
      es: 'Polonia',
      fr: 'Pologne',
      it: 'Polonia',
      pt: 'Polônia',
    },
    isoCode: 'PL',
    flagPath: '/flags/pl.svg',
  },
  {
    name: {
      de: 'Italien',
      en: 'Italy',
      es: 'Italia',
      fr: 'Italie',
      it: 'Italia',
      pt: 'Itália',
    },
    isoCode: 'IT',
    flagPath: '/flags/it.svg',
  },
  {
    name: {
      de: 'Portugal',
      en: 'Portugal',
      es: 'Portugal',
      fr: 'Portugal',
      it: 'Portogallo',
      pt: 'Portugal',
    },
    isoCode: 'PT',
    flagPath: '/flags/pt.svg',
  },
  {
    name: {
      de: 'Griechenland',
      en: 'Greece',
      es: 'Grecia',
      fr: 'Grèce',
      it: 'Grecia',
      pt: 'Grécia',
    },
    isoCode: 'GR',
    flagPath: '/flags/gr.svg',
  },
  {
    name: {
      de: 'Kroatien',
      en: 'Croatia',
      es: 'Croacia',
      fr: 'Croatie',
      it: 'Croazia',
      pt: 'Croácia',
    },
    isoCode: 'HR',
    flagPath: '/flags/hr.svg',
  },
  {
    name: {
      de: 'Brasilien',
      en: 'Brazil',
      es: 'Brasil',
      fr: 'Brésil',
      it: 'Brasile',
      pt: 'Brasil',
    },
    isoCode: 'BR',
    flagPath: '/flags/br.svg',
  },
  {
    name: {
      de: 'Mexiko',
      en: 'Mexico',
      es: 'México',
      fr: 'Mexique',
      it: 'Messico',
      pt: 'México',
    },
    isoCode: 'MX',
    flagPath: '/flags/mx.svg',
  },
  {
    name: {
      de: 'Kolumbien',
      en: 'Colombia',
      es: 'Colombia',
      fr: 'Colombie',
      it: 'Colombia',
      pt: 'Colômbia',
    },
    isoCode: 'CO',
    flagPath: '/flags/co.svg',
  },
  {
    name: {
      de: 'Venezuela',
      en: 'Venezuela',
      es: 'Venezuela',
      fr: 'Venezuela',
      it: 'Venezuela',
      pt: 'Venezuela',
    },
    isoCode: 'VE',
    flagPath: '/flags/ve.svg',
  },
  {
    name: {
      de: 'Peru',
      en: 'Peru',
      es: 'Perú',
      fr: 'Pérou',
      it: 'Perù',
      pt: 'Peru',
    },
    isoCode: 'PE',
    flagPath: '/flags/pe.svg',
  },
  {
    name: {
      de: 'Argentinien',
      en: 'Argentina',
      es: 'Argentina',
      fr: 'Argentine',
      it: 'Argentina',
      pt: 'Argentina',
    },
    isoCode: 'AR',
    flagPath: '/flags/ar.svg',
  },
  {
    name: {
      de: 'Bolivien',
      en: 'Bolivia',
      es: 'Bolivia',
      fr: 'Bolivie',
      it: 'Bolivia',
      pt: 'Bolívia',
    },
    isoCode: 'BO',
    flagPath: '/flags/bo.svg',
  },
  {
    name: {
      de: 'Vereinigte Staaten',
      en: 'United States',
      es: 'Estados Unidos',
      fr: 'États-Unis',
      it: 'Stati Uniti',
      pt: 'Estados Unidos',
    },
    isoCode: 'US',
    flagPath: '/flags/us.svg',
  },
  {
    name: {
      de: 'Kanada',
      en: 'Canada',
      es: 'Canadá',
      fr: 'Canada',
      it: 'Canada',
      pt: 'Canadá',
    },
    isoCode: 'CA',
    flagPath: '/flags/ca.svg',
  },
];
