import { Inter } from 'next/font/google';
import { AppHeader } from '@components/AppHeader';
import { countryListFinder } from '@country/application/country-list-finder';
import { ChakraProvider } from '@shared/presentation/chakra-ui/chakra-provider';
import '../global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AppRootLayout = async ({ children }: { children: React.ReactNode }) => {
  const countries = await countryListFinder({ isAvailableToSearch: true });

  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <AppHeader countries={countries} />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
};

export default AppRootLayout;
